# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import pytest
import openpyxl

class TestLoginfail():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  #excel oku
  #verileri çıkart (dış kaynaktan gelen verileri data klasöründe tutarız)
  #testte kullan
  def readUserDataFromExcel():
    excelFile = openpyxl.load_workbook("data/userFailData.xlsx")
    selectedSheet = excelFile["Sheet1"]
    rows = selectedSheet.max_row
    data = []

    for i in range(2,rows+1):
      username = selectedSheet.cell(i, 1).value
      password = selectedSheet.cell(i, 2).value
      tupleExample = (username,password)
      data.append(tupleExample)

    return data

  
  ## @pytest.mark.parametrize("username,password",[("standard_user","123"),("123","123")])
  @pytest.mark.parametrize("username,password",readUserDataFromExcel())
  def test_loginfail(self,username,password):
    self.driver.get("https://www.saucedemo.com/")
    self.driver.set_window_size(1552, 832)
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "*[data-test=\"username\"]")))
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").send_keys(username)
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "*[data-test=\"password\"]")))
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").send_keys(password)
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "*[data-test=\"login-button\"]")))
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-button\"]").click()
  
